using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Numerics;

namespace EnitityFrameWorkReWrite.EnumsStaticClasses {
    public static class SetEnum {
        #region Core_Sets
        public static BigInteger NONE = 0;
        public static BigInteger LEA = 1 << 0;
        public static BigInteger LEB = 1 << 1;
        public static BigInteger II_ED = 1 << 2;
        public static BigInteger III_ED = 1 << 3;
        public static BigInteger IV_ED = 1 << 4;
        public static BigInteger V_ED = 1 << 6;
        public static BigInteger VI_ED = 1 << 7;
        public static BigInteger VIII_ED = 1 << 8;
        public static BigInteger IX_ED = 1 << 9;
        public static BigInteger X_ED = 1 << 10;
        public static BigInteger M10 = 1 << 11;
        public static BigInteger M11 = 1 << 12;
        public static BigInteger M12 = 1 << 13;
        public static BigInteger M13 = 1 << 14;
        public static BigInteger M14 = 1 << 15;
        public static BigInteger M15 = 1 << 16;
        public static BigInteger ORI = 1 << 17;
        public static BigInteger M19 = 1 << 18;
        #endregion

        #region Expansion_Sets
        public static BigInteger ARN = 1 << 19;
        public static BigInteger ATQ = 1 << 20;
        public static BigInteger LEG = 1 << 21;
        public static BigInteger DRK = 1 << 22;
        public static BigInteger FEM = 1 << 23;
        public static BigInteger ICE = 1 << 24;
        public static BigInteger HML = 1 << 25;
        public static BigInteger ALL = 1 << 26;
        public static BigInteger MIR = 1 << 27;
        public static BigInteger VIS = 1 << 28;
        public static BigInteger WTH = 1 << 29;
        public static BigInteger TMP = 1 << 30;
        public static BigInteger STH = 1 << 31;
        public static BigInteger EXO = 1 << 32;
        public static BigInteger USG = 1 << 33;
        public static BigInteger ULG = 1 << 34;
        public static BigInteger UDS = 1 << 35;
        public static BigInteger MMQ = 1 << 36;
        public static BigInteger NMS = 1 << 37;
        public static BigInteger PCY = 1 << 38;
        public static BigInteger INV = 1 << 39;
        public static BigInteger PLS = 1 << 40;
        public static BigInteger APC = 1 << 41;
        public static BigInteger ODY = 1 << 42;
        public static BigInteger TOR = 1 << 43;
        public static BigInteger JUD = 1 << 44;
        public static BigInteger ONS = 1 << 45;
        public static BigInteger LGN = 1 << 46;
        public static BigInteger SCG = 1 << 47;
        public static BigInteger MRD = 1 << 48;
        public static BigInteger DST = 1 << 49;
        public static BigInteger V_DN = 1 << 50;
        public static BigInteger CHK = 1 << 51;
        public static BigInteger BOK = 1 << 52;
        public static BigInteger SOK = 1 << 53;
        public static BigInteger RAV = 1 << 54;
        public static BigInteger GPT = 1 << 55;
        public static BigInteger DIS = 1 << 56;
        public static BigInteger CSP = 1 << 57;
        public static BigInteger TSP = 1 << 58;
        public static BigInteger PLC = 1 << 59;
        public static BigInteger FUT = 1 << 60;
        public static BigInteger LWR = 1 << 61;
        public static BigInteger MOR = 1 << 62;
        public static BigInteger SHM = 1 << 63;
        public static BigInteger EVE = 1 << 64;
        public static BigInteger ALA = 1 << 65;
        public static BigInteger CON = 1 << 66;
        public static BigInteger ARB = 1 << 67;
        public static BigInteger ZEN = 1 << 68;
        public static BigInteger WWK = 1 << 69;
        public static BigInteger ROE = 1 << 70;
        public static BigInteger SOM = 1 << 71;
        public static BigInteger MBS = 1 << 72;
        public static BigInteger NPH = 1 << 73;
        public static BigInteger ISD = 1 << 74;
        public static BigInteger DKA = 1 << 75;
        public static BigInteger AVR = 1 << 76;
        public static BigInteger RTR = 1 << 77;
        public static BigInteger GTC = 1 << 78;
        public static BigInteger DGM = 1 << 79;
        public static BigInteger THS = 1 << 80;
        public static BigInteger BNG = 1 << 81;
        public static BigInteger JOU = 1 << 82;
        public static BigInteger KTK = 1 << 83;
        public static BigInteger FRF = 1 << 84;
        public static BigInteger DTK = 1 << 85;
        public static BigInteger BFZ = 1 << 86;
        public static BigInteger OGW = 1 << 87;
        public static BigInteger SOI = 1 << 88;
        public static BigInteger EMN = 1 << 89;
        public static BigInteger KLD = 1 << 90;
        public static BigInteger AER = 1 << 91;
        public static BigInteger AKH = 1 << 92;
        public static BigInteger HOU = 1 << 93;
        public static BigInteger XLN = 1 << 94;
        public static BigInteger RIX = 1 << 95;
        public static BigInteger DOM = 1 << 96;
#endregion
    }
}
